name: Build redoc
on:
  push:
    branches:
      - master
      - redoc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: npm ci
    - name: Build docs
      run: npm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-page
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        publish_dir: ./public
        force_orphan: true
        exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md'
        #cname: servicepos
